import test from 'node:test';
import assert from 'node:assert/strict';
import {ACTIONS,advanceGame,createGame,startGame,submitMain,submitDelayed,submitRps,publicGame,rematch,type ActionInput,type GameState} from './game.ts';

const make=(n=2)=>startGame(createGame(Array.from({length:n},(_,i)=>({id:String.fromCharCode(97+i),name:`玩家${i+1}`,seat:i+1}))),0);
const main=(g:GameState,inputs:ActionInput[])=>{inputs.forEach((input,i)=>submitMain(g,String.fromCharCode(97+i),input));advanceGame(g,1);};
const save=(g:GameState)=>JSON.parse(JSON.stringify(g)) as GameState;
const order=(g:GameState)=>{submitRps(g,'a','priority','rock');submitRps(g,'b','priority','scissors');advanceGame(g,2);};
const finishDuel=(g:GameState)=>{for(const d of g.rps){submitRps(g,d.attackerId,d.id,'rock');submitRps(g,d.targetId,d.id,'scissors');}advanceGame(g,4);};

for(const [id,cost,heal] of [['smallHeal',3,1],['bigHeal',5,2]] as const){
  test(`${id}: 正常支付，可超过10血，仅整轮末恢复一次`,()=>{const g=make();g.players[0].points=cost;main(g,[{id},{id:'skip'}]);assert.equal(g.players[0].hp,10+heal);assert.equal(g.players[0].points,0);assert.deepEqual(g.pendingHeals,[]);advanceGame(g,2);assert.equal(g.players[0].hp,10+heal);assert.equal(g.reveal?.hpChanges[0].after,10+heal);});
  test(`${id}: 点数不足不能爆点或防御`,()=>{const g=make();g.players[0].points=cost-1;g.players[1].points=1;main(g,[{id,burst:99},{id:'gun',targetId:'a'}]);assert.equal(g.players[0].hp,9);assert.equal(g.players[0].points,cost-1);assert.match(g.events.join(''),/资源不足/);});
}
for(const id of ['gun','punch','execute','super','push','pull','snap','plastic','iron','cottonShovel','popShield','popWater'] as const){
  test(`治疗抵挡一次完整${id}，不回血、不猜拳、不爆已有盾水`,()=>{const g=make();Object.assign(g.players[0],{points:20,shields:1,waters:1});Object.assign(g.players[1],{points:20,fists:8,cotton:1,shields:1,waters:1});main(g,[{id:'smallHeal'},{id,targetId:'a',count:8}]);assert.equal(g.players[0].hp,10);assert.equal(g.players[0].points,17);assert.equal(g.players[0].shields,1);assert.equal(g.players[0].waters,1);assert.equal(g.phase,'reveal');assert.equal(g.rps.length,0);assert.match(g.events.join(''),/治疗被.*打爆/);});
}
test('密集气功清点但治疗仍恢复',()=>{const g=make();g.players.forEach(p=>p.points=10);main(g,[{id:'bigHeal'},{id:'mass'}]);assert.equal(g.players[0].points,0);assert.equal(g.players[0].hp,12);assert.doesNotMatch(g.events.join(''),/打爆/);});
test('第一次来源按座位吸收，后续来源正常造成伤害',()=>{const g=make(3);g.players.forEach(p=>p.points=20);main(g,[{id:'smallHeal'},{id:'gun',targetId:'a',count:8},{id:'gun',targetId:'a',count:2}]);assert.equal(g.players[0].hp,8);assert.match(g.events.join(''),/玩家2的枪打爆/);});
test('主治疗一直等到延判结束，跨JSON持久化',()=>{let g=make();g.players.forEach(p=>p.points=20);main(g,[{id:'smallHeal'},{id:'raiseFist'}]);assert.equal(g.phase,'delayed');assert.equal(g.players[0].hp,10);g=save(g);submitDelayed(g,'b',[]);advanceGame(g,2);assert.equal(g.players[0].hp,11);assert.deepEqual(g.pendingHeals,[]);advanceGame(g,6000);assert.equal(g.players[0].hp,11);assert.deepEqual(g.pendingHeals,[]);rematch(g,7000);assert.equal(g.players[0].hp,10);});
test('延判枪打爆主治疗，不扣血也不回血',()=>{const g=make();g.players.forEach(p=>p.points=20);main(g,[{id:'bigHeal'},{id:'raiseFist'}]);submitDelayed(g,'b',[{id:'gun',targetId:'a'}]);advanceGame(g,2);assert.equal(g.players[0].hp,10);assert.deepEqual(g.pendingHeals,[]);});
test('无关玩家铲子猜拳暂停期间不提前回血',()=>{let g=make(4);g.players.forEach(p=>p.points=20);main(g,[{id:'smallHeal'},{id:'iron',targetId:'c'},{id:'guard'},{id:'raiseFist'}]);assert.equal(g.phase,'rps');assert.equal(g.players[0].hp,10);g=save(g);finishDuel(g);assert.equal(g.phase,'delayed');assert.equal(g.players[0].hp,10);submitDelayed(g,'d',[{id:'gun',targetId:'a'}]);advanceGame(g,5);assert.equal(g.players[0].hp,10);assert.deepEqual(g.pendingHeals,[]);});
for(const strike of [false,true])test(`延判治疗跨铲子猜拳保存，随后${strike?'被攻击打爆':'最终回血'}`,()=>{let g=make(3);g.players.forEach(p=>p.points=24);main(g,[{id:'bigShield'},{id:'bigShield'},{id:'skip'}]);order(g);submitDelayed(g,'a',[{id:'smallHeal'},{id:'iron',targetId:'c'}]);submitDelayed(g,'b',[strike?{id:'gun',targetId:'a'}:{id:'accumulate'}]);advanceGame(g,3);assert.equal(g.phase,'rps');assert.equal(g.players[0].hp,10);g=save(g);finishDuel(g);assert.equal(g.phase,'reveal');assert.equal(g.players[0].hp,strike?10:11);assert.equal(g.players[0].shields,1);assert.deepEqual(g.pendingHeals,[]);});
for(const count of [0,1,2])test(`两份治疗按先后逐份吸收${count}次推，剩余的轮末恢复`,()=>{const g=make();g.players.forEach(p=>p.points=30);main(g,[{id:'bigShield'},{id:'bigShield'}]);order(g);submitDelayed(g,'a',[{id:'smallHeal'},{id:'bigHeal'}]);submitDelayed(g,'b',Array.from({length:count},()=>({id:'push',targetId:'a'})));advanceGame(g,3);assert.equal(g.players[0].hp,[13,12,10][count]);assert.equal(g.players[0].points,18);});
test('延判真伤打爆治疗，既不扣血也不消耗盾',()=>{const g=make();g.players.forEach(p=>p.points=24);main(g,[{id:'bigShield'},{id:'bigShield'}]);order(g);submitDelayed(g,'a',[{id:'smallHeal'}]);submitDelayed(g,'b',[{id:'shieldThunder'}]);advanceGame(g,3);assert.equal(g.players[0].hp,10);assert.equal(g.players[0].shields,1);assert.deepEqual(g.pendingHeals,[]);});
test('自扣血不触发治疗，已淘汰不能靠待治疗复活',()=>{const g=make();g.players.forEach(p=>p.points=24);g.players[0].hp=1;main(g,[{id:'bigShield'},{id:'skip'}]);submitDelayed(g,'a',[{id:'smallHeal'},{id:'knife3'}]);advanceGame(g,2);assert.equal(g.players[0].alive,false);assert.equal(g.players[0].hp,-1);assert.deepEqual(g.pendingHeals,[]);assert.doesNotMatch(g.events.join(''),/恢复/);});
test('治疗失败的铲子仍进入猜拳，不能凭未支付动作挡住铲子',()=>{const g=make();g.players[1].points=4;main(g,[{id:'smallHeal'},{id:'iron',targetId:'a'}]);assert.equal(g.phase,'rps');finishDuel(g);assert.equal(g.players[0].hp,5);});
test('旧状态兼容、公开状态只显示I类动作，不包含余额或待治疗内部数据',()=>{const g=make();delete g.pendingHeals;g.players.forEach(p=>p.points=10);main(g,[{id:'smallHeal'},{id:'raiseFist'}]);const json=JSON.stringify(publicGame(g));assert.doesNotMatch(json,/"points"|"pendingHeals"|"swap"|"roundActionResults"/);assert.deepEqual(ACTIONS.filter(a=>a.category==='I').map(a=>[a.id,a.cost,Boolean(a.burst)]),[['smallHeal',3,false],['bigHeal',5,false]]);});
for(const id of ['five9','five10'] as const)for(const shots of [1,2])test(`延判治疗再${id}遇${shots}次枪：治疗先吸收首源，五换特殊只处理后续来源`,()=>{const g=make();g.players.forEach(p=>p.points=30);main(g,[{id:'bigShield'},{id:'bigShield'}]);order(g);submitDelayed(g,'a',[{id:'smallHeal'},{id}]);submitDelayed(g,'b',Array.from({length:shots},()=>({id:'gun' as const,targetId:'a'})));advanceGame(g,3);const a=g.players[0];assert.equal(a.hp,id==='five10'&&shots===2?5:10);assert.equal(a.points,shots===2?0:id==='five10'?23:22);assert.equal(a.shields,id==='five10'&&shots===2?0:1);assert.equal(a.swap?.triggered,shots===2);assert.deepEqual(g.pendingHeals,[]);});
test('治疗+5换10遇密集：密不打爆治疗，五换副作用仍保留，存活后整轮回血',()=>{const g=make();g.players.forEach(p=>p.points=30);main(g,[{id:'bigShield'},{id:'bigShield'}]);order(g);submitDelayed(g,'a',[{id:'smallHeal'},{id:'five10'}]);submitDelayed(g,'b',[{id:'mass'}]);advanceGame(g,3);assert.equal(g.players[0].hp,6);assert.equal(g.players[0].points,0);assert.equal(g.players[0].shields,0);assert.match(g.events.join(''),/恢复 1 血/);assert.doesNotMatch(g.events.join(''),/治疗被/);});
test('治疗+5换9遇拉：治疗先挡来袭，原点保留且治疗不回血',()=>{const g=make();g.players.forEach(p=>p.points=30);main(g,[{id:'bigShield'},{id:'bigShield'}]);order(g);submitDelayed(g,'a',[{id:'smallHeal'},{id:'five9'}]);submitDelayed(g,'b',[{id:'pull',targetId:'a'}]);advanceGame(g,3);assert.equal(g.players[0].hp,10);assert.equal(g.players[0].points,22);assert.match(g.events.join(''),/治疗被.*拉打爆/);});
